name: Build & Push Docker Images

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        image: [] # This will be populated by the list_images step
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List images for matrix
        id: list_images
        run: |
          IMAGES=$(ls docker | tr '\n' ' ')
          echo "images_json=[\"$(echo $IMAGES | sed 's/ /","/g')\"]" >> $GITHUB_OUTPUT

      - name: Set matrix for job
        run: |
          echo "Using images: ${{ steps.list_images.outputs.images_json }}"
          echo "::set-output name=matrix::{\"image\":${{ steps.list_images.outputs.images_json }}}"
        id: set_matrix # Give this step an id to reference its output if needed later, though matrix is set directly for the job

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: network=host

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: docker/${{ matrix.image }}
          file: docker/${{ matrix.image }}/Dockerfile
          push: true
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
            linux/s390x
            linux/ppc64le
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:latest
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:${{ github.sha }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:${{ github.sha }}
